// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// Bu dosya Firebase yapılandırma ayarlarını içerir.
// Otomatik olarak oluşturulmuştur. Manuel düzenlemeyin.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACZd5x5BhGcdt8qAxBGhQirN7D1UICrRs',
    appId: '1:30737433081:web:64196540d322919cf0fd28',
    messagingSenderId: '30737433081',
    projectId: 'ferdi-baba',
    authDomain: 'ferdi-baba.firebaseapp.com',
    databaseURL: 'https://ferdi-baba-default-rtdb.firebaseio.com',
    storageBucket: 'ferdi-baba.appspot.com',
    measurementId: 'G-JD7WPTMM4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCixMMs8z3372BwDxd8TcH3DZoCwcGLAvo',
    appId: '1:30737433081:android:38174ff863301d08f0fd28',
    messagingSenderId: '30737433081',
    projectId: 'ferdi-baba',
    databaseURL: 'https://ferdi-baba-default-rtdb.firebaseio.com',
    storageBucket: 'ferdi-baba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXxPk2vg618sfYRlt6AYXi2yMyoPwjxJg',
    appId: '1:30737433081:ios:b450595b9dc48262f0fd28',
    messagingSenderId: '30737433081',
    projectId: 'ferdi-baba',
    databaseURL: 'https://ferdi-baba-default-rtdb.firebaseio.com',
    storageBucket: 'ferdi-baba.appspot.com',
    androidClientId:
        '30737433081-55rlv3g54um1280hg6tbee5f7hf3v5fh.apps.googleusercontent.com',
    iosClientId:
        '30737433081-qvil07d9gndl9gj45044hiqmpr44oe7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneNote',
  );
}
